FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

ENV PORT=5173
ENV HOST=0.0.0.0

EXPOSE 5173 

CMD ["yarn", "run", "dev", "--host", "0.0.0.0"]
